"""DSL AST package facade.


功能说明:
- 聚合 AST 节点与解析入口，提供稳定的 `kernel_gen.dsl.ast` 导入路径。
- 只做导出，不在本文件内实现节点定义或解析逻辑。

API 列表:
- `parse(fn: Callable[..., DslFunctionReturn], *runtime_args: DslRuntimeArg) -> ModuleAST`
- `parse_function(fn: Callable[..., DslFunctionReturn], *runtime_args: DslRuntimeArg) -> FunctionAST`
- `DslAstVisitor(fn: DslCallable, runtime_args: tuple[DslRuntimeArg, ...] = ())`
- `DSLNode` / `ValueAST` / `StatementAST`
- `ModuleAST` / `FunctionAST` / `BlockAST` / `BoundExprAST` / `ReturnAST` / `ForAST` / `IfAST` / `CallAST`
- `MemoryAST` / `SymbolDimAST` / `ConstValueAST` / `BoolValueAST` / `SymbolListAST`
- `Diagnostic` / `SourceLocation` / `AttrAST` / `PythonObjectAttrAST` / `ListAST` / `TupleAST`
- `IntTypeAttrAST` / `FloatTypeAttrAST` / `BoolTypeAttrAST` / `MemorySpaceAttrAST`
- `KernelBinaryElewiseAST` / `KernelAddAST` / `KernelMatmulAST` / `KernelImg2Col1dAST` / `KernelImg2Col2dAST`
- 其余公开 AST 节点类由 `kernel_gen.dsl.ast.nodes` 定义并经本包根导出。

使用示例:
- from kernel_gen.dsl.ast import FunctionAST, parse_function
- func_ast = parse_function(kernel, lhs)

关联文件:
- spec: spec/dsl/ast/__init__.md
- test: test/dsl/ast/test_parser.py
- 功能实现: kernel_gen/dsl/ast/__init__.py
"""

from __future__ import annotations

from .nodes import (
    ArchBarrierAST,
    ArchGetBlockIdAST,
    ArchGetBlockNumAST,
    ArchGetDynamicMemoryAST,
    ArchGetSubthreadIdAST,
    ArchGetSubthreadNumAST,
    ArchGetThreadIdAST,
    ArchGetThreadNumAST,
    ArchLaunchKernelAST,
    ArchQueryAST,
    AttrAST,
    BlockAST,
    BoolTypeAttrAST,
    BoolValueAST,
    BoundExprAST,
    CallAST,
    ConstValueAST,
    ConvAST,
    Diagnostic,
    DmaAllocAST,
    DmaCastAST,
    DmaCopyAST,
    DmaDesliceAST,
    DmaFillAST,
    DmaFlattenAST,
    DmaFreeAST,
    DmaLoadAST,
    DmaReshapeAST,
    DmaSliceAST,
    DmaStoreAST,
    DmaViewAST,
    DSLNode,
    FCAST,
    FloatTypeAttrAST,
    ForAST,
    FunctionAST,
    IfAST,
    IntTypeAttrAST,
    KernelAddAST,
    KernelBinaryElewiseAST,
    KernelDivAST,
    KernelEqAST,
    KernelGeAST,
    KernelGtAST,
    KernelImg2Col1dAST,
    KernelImg2Col2dAST,
    KernelLeAST,
    KernelLtAST,
    KernelMatmulAST,
    KernelMulAST,
    KernelNeAST,
    KernelSubAST,
    KernelTrueDivAST,
    ListAST,
    MatmulAST,
    MemoryAST,
    MemorySpaceAttrAST,
    NnAddAST,
    ModuleAST,
    NnBroadcastAST,
    NnBroadcastToAST,
    NnEqAST,
    NnExpAST,
    NnFloorDivAST,
    NnGeAST,
    NnGtAST,
    NnHardSigmoidAST,
    NnImg2Col1dAST,
    NnImg2Col2dAST,
    NnLeAST,
    NnLeakyReluAST,
    NnLtAST,
    NnMulAST,
    NnNeAST,
    NnReduceAST,
    NnReduceMaxAST,
    NnReduceMinAST,
    NnReduceSumAST,
    NnReluAST,
    NnSigmoidAST,
    NnSoftmaxAST,
    NnSubAST,
    NnTanhAST,
    NnTransposeAST,
    NnTrueDivAST,
    PythonObjectAttrAST,
    ReturnAST,
    StatementAST,
    SourceLocation,
    SymbolAddAST,
    SymbolBinaryAST,
    SymbolCompareAST,
    SymbolDimAST,
    SymbolEqAST,
    SymbolFloorDivAST,
    SymbolGeAST,
    SymbolGtAST,
    SymbolLeAST,
    SymbolListAST,
    SymbolLtAST,
    SymbolMaxAST,
    SymbolMinAST,
    SymbolMulAST,
    SymbolNeAST,
    SymbolSubAST,
    SymbolToFloatAST,
    SymbolTrueDivAST,
    TensorAxisAccessAST,
    TupleAST,
    ValueAST,
)
from .dsl_ast import DslAstVisitor
from .parser import parse, parse_function

__all__ = [
    "ArchBarrierAST",
    "ArchGetBlockIdAST",
    "ArchGetBlockNumAST",
    "ArchGetDynamicMemoryAST",
    "ArchGetSubthreadIdAST",
    "ArchGetSubthreadNumAST",
    "ArchGetThreadIdAST",
    "ArchGetThreadNumAST",
    "ArchLaunchKernelAST",
    "ArchQueryAST",
    "AttrAST",
    "BlockAST",
    "BoolTypeAttrAST",
    "BoolValueAST",
    "BoundExprAST",
    "CallAST",
    "ConstValueAST",
    "ConvAST",
    "Diagnostic",
    "DmaAllocAST",
    "DmaCastAST",
    "DmaCopyAST",
    "DmaDesliceAST",
    "DmaFillAST",
    "DmaFlattenAST",
    "DmaFreeAST",
    "DmaLoadAST",
    "DmaReshapeAST",
    "DmaSliceAST",
    "DmaStoreAST",
    "DmaViewAST",
    "DSLNode",
    "DslAstVisitor",
    "FCAST",
    "FloatTypeAttrAST",
    "ForAST",
    "FunctionAST",
    "IfAST",
    "IntTypeAttrAST",
    "KernelAddAST",
    "KernelBinaryElewiseAST",
    "KernelDivAST",
    "KernelEqAST",
    "KernelGeAST",
    "KernelGtAST",
    "KernelImg2Col1dAST",
    "KernelImg2Col2dAST",
    "KernelLeAST",
    "KernelLtAST",
    "KernelMatmulAST",
    "KernelMulAST",
    "KernelNeAST",
    "KernelSubAST",
    "KernelTrueDivAST",
    "ListAST",
    "MatmulAST",
    "MemoryAST",
    "MemorySpaceAttrAST",
    "NnAddAST",
    "ModuleAST",
    "NnBroadcastAST",
    "NnBroadcastToAST",
    "NnEqAST",
    "NnExpAST",
    "NnFloorDivAST",
    "NnGeAST",
    "NnGtAST",
    "NnHardSigmoidAST",
    "NnImg2Col1dAST",
    "NnImg2Col2dAST",
    "NnLeAST",
    "NnLeakyReluAST",
    "NnLtAST",
    "NnMulAST",
    "NnNeAST",
    "NnReduceAST",
    "NnReduceMaxAST",
    "NnReduceMinAST",
    "NnReduceSumAST",
    "NnReluAST",
    "NnSigmoidAST",
    "NnSoftmaxAST",
    "NnSubAST",
    "NnTanhAST",
    "NnTransposeAST",
    "NnTrueDivAST",
    "PythonObjectAttrAST",
    "ReturnAST",
    "StatementAST",
    "SourceLocation",
    "SymbolAddAST",
    "SymbolBinaryAST",
    "SymbolCompareAST",
    "SymbolDimAST",
    "SymbolEqAST",
    "SymbolFloorDivAST",
    "SymbolGeAST",
    "SymbolGtAST",
    "SymbolLeAST",
    "SymbolListAST",
    "SymbolLtAST",
    "SymbolMaxAST",
    "SymbolMinAST",
    "SymbolMulAST",
    "SymbolNeAST",
    "SymbolSubAST",
    "SymbolToFloatAST",
    "SymbolTrueDivAST",
    "TensorAxisAccessAST",
    "TupleAST",
    "ValueAST",
    "parse",
    "parse_function",
]
